name: Publish Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and test the project
      - name: Build with Maven
        run: mvn clean install

  publish:
    name: Publish to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # # Configure Maven settings.xml
      # - name: Configure Maven settings.xml
      #   run: |
      #     mkdir -p ~/.m2
      #     cat <<EOF > ~/.m2/settings.xml
      #     <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      #               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      #               xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
      #         <servers>
      #             <server>
      #                 <id>github</id>
      #                 <username>${{ github.actor }}</username>
      #                 <password>${{ secrets.GITHUB_TOKEN }}</password>
      #             </server>
      #         </servers>
      #     </settings>
      #     EOF

      # # Publish to GitHub Packages
      # - name: Publish to GitHub Packages
      #   run: mvn deploy -DskipTests